const latex = `% Generated by md-latex — https://github.com/iamvirul/md-latex
\\documentclass[11pt, a4paper]{article}

% ── Encoding & fonts ──────────────────────────────────────
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{lmodern}          % Better font rendering

% ── Page geometry ─────────────────────────────────────────
\\usepackage[
  top=1in, bottom=1in,
  left=1.25in, right=1.25in,
  headheight=14pt
]{geometry}

% ── Mathematics ───────────────────────────────────────────
\\usepackage{amsmath}
\\usepackage{amssymb}
\\usepackage{amsthm}
\\usepackage{mathtools}

% ── Graphics & floats ─────────────────────────────────────
\\usepackage{graphicx}
\\usepackage{float}
\\usepackage[labelfont=bf, font=small]{caption}
\\usepackage{subcaption}

% ── Tables ────────────────────────────────────────────────
\\usepackage{booktabs}
\\usepackage{array}
\\usepackage{multirow}

% ── Colors ────────────────────────────────────────────────
\\usepackage[dvipsnames, table]{xcolor}
\\definecolor{codegreen}{rgb}{0.13,0.55,0.13}
\\definecolor{codegray}{rgb}{0.5,0.5,0.5}
\\definecolor{codepurple}{rgb}{0.42,0.18,0.62}
\\definecolor{codeblue}{rgb}{0.05,0.40,0.70}
\\definecolor{backcolour}{rgb}{0.97,0.97,0.97}

% ── Code listings ─────────────────────────────────────────
\\usepackage{listings}
\\lstset{
  backgroundcolor=\\color{backcolour},
  commentstyle=\\color{codegreen}\\itshape,
  keywordstyle=\\color{codeblue}\\bfseries,
  numberstyle=\\tiny\\color{codegray},
  stringstyle=\\color{codepurple},
  basicstyle=\\ttfamily\\small,
  breakatwhitespace=false,
  breaklines=true,
  captionpos=b,
  keepspaces=true,
  numbers=left,
  numbersep=8pt,
  showspaces=false,
  showstringspaces=false,
  showtabs=false,
  tabsize=2,
  frame=single,
  framesep=4pt,
  rulecolor=\\color{gray!30},
  xleftmargin=12pt,
}

% ── Hyperlinks ────────────────────────────────────────────
\\usepackage[
  colorlinks=true,
  linkcolor=NavyBlue,
  citecolor=ForestGreen,
  urlcolor=MidnightBlue,
  pdftitle={My Research Paper},
  pdfauthor={Jane Smith},
  pdfsubject={},
  bookmarksnumbered=true,
  pdfpagemode=UseOutlines,
]{hyperref}

% ── Typography ────────────────────────────────────────────
\\usepackage{microtype}        % Subtle character protrusion & kerning
\\usepackage{parskip}          % Paragraph spacing instead of indent
\\usepackage{setspace}

% ── User packages ─────────────────────────────────────────
% (none)

% ── Document metadata ────────────────────────────────────
\\title{My Research Paper}
\\author{Jane Smith}
\\date{\\today}

\\begin{document}

\\maketitle


% ── Body ────────────────────────────────────────────────
\\section{Introduction}

Welcome to \\textbf{md-latex} — write \\textit{Markdown}, get LaTeX.

\\subsection{Mathematical Framework}

The quadratic formula is $x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$.

Display math works too:

\\[
\\int_{-\\infty}^{\\infty} e^{-x^2} \\, dx = \\sqrt{\\pi}
\\]

\\subsection{Features}

\\begin{itemize}
\\item Real-time transpilation
\\item GFM tables → \\texttt{tabular}
\\item Math via KaTeX in preview
\\item Export to \\texttt{.tex}
\\end{itemize}

\\subsection{Code Example}

\\begin{lstlisting}[language=python]
def transpile(markdown: str) -> str:
    """Convert Markdown to LaTeX."""
    ast = parse(markdown)
    return emit(ast)
\\end{lstlisting}

\\subsection{Results Table}

\\begin{table}[H]
  \\centering
  \\begin{tabular}{|l|l|l|}
    \\hline
    Feature & Supported & Notes \\\\
    \\hline
    Headings & ✓ & H1–H6 mapping \\\\
    Math & ✓ & KaTeX preview \\\\
    Tables & ✓ & GFM tabular \\\\
    Citations & ✓ & [\\cite{key}] syntax \\\\
    \\hline
  \\end{tabular}
\\end{table}

\\begin{quote}
"Mathematics is the language in which God has written the universe." — Galileo
\\end{quote}

See [\\cite{galilei1623}] for the original quote.

\\noindent\\rule{\\linewidth}{0.4pt}

\\begin{enumerate}
\\item Write Markdown
\\item Get LaTeX
\\item Publish your paper
\\end{enumerate}

\\end{document}
`;

async function run() {
  const params = new URLSearchParams({ text: latex });
  const res = await fetch('https://latexonline.cc/compile', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: params,
  });
  if (!res.ok) {
    const text = await res.text();
    console.error("COMPILE FAILED:");
    console.error(text);
  } else {
    console.log("COMPILE SUCCESS!");
  }
}
run();
